### ISSUE TITLE
No uncompressed version?

### ISSUE THREAD

**Issue by jenstornell** [yanatan16/nanoajax#12]
This works great! However there seems to be a `nanoajax.min.js` but no `nanoajax.js`?

I prefer compressing the js files myself when merging the js to one compact file.

**Comment by jenstornell** [comment]
In case you do not update it anymore, here is an unminified version:

``` js
! function(e, t) {
    function n() {
        if (t.XMLHttpRequest) return new t.XMLHttpRequest;
        try {
            return new t.ActiveXObject("MSXML2.XMLHTTP.3.0")
        } catch (e) {}
        throw new Error("no xmlhttp request able to be created")
    }

    function r(e, t, n) {
        e[t] = e[t] || n
    }
    t.nanoajax = e, e.ajax = function(e, t) {
        "string" == typeof e && (e = {
            url: e
        });
        var a = e.headers || {}, o = e.body,
            u = e.method || (o ? "POST" : "GET"),
            i = e.withCredentials || !1,
            s = n();
        s.onreadystatechange = function() {
            4 == s.readyState && t(s.status, s.responseText, s)
        }, o && (r(a, "X-Requested-With", "XMLHttpRequest"), r(a, "Content-Type", "application/x-www-form-urlencoded")), s.open(u, e.url, !0), s.withCredentials = i;
        for (var c in a) s.setRequestHeader(c, a[c]);
        s.send(o)
    }
}({}, function() {
    return this
}());
```

**Comment by loup-brun** [comment]
Have a look at `index.js`

**Comment by jenstornell** [comment]
I searched for `nanoajax` in `index.js` but it could not be found so I guess it does not work?

**Comment by loup-brun** [comment]
Well, if you look at the `make` file, the minifier wraps `index.js` with `nanoajax`, so I guess you can wrap it yourself, naming it however you like.

**Comment by yanatan16** [comment]
@jenstornell [index.js](https://github.com/yanatan16/nanoajax/blob/master/index.js) _is_ the unminified version you are looking for. It is written as a [CommonJS](http://wiki.commonjs.org/wiki/Modules/1.1) module, which is compatible with many tools, notably [browserify](http://browserify.org/).

In [make](https://github.com/yanatan16/nanoajax/blob/master/make), we call `uglifyjs` with the `--wrap nanoajax` argument, which wraps our CommonJS module in one large function and assigns `exports` to `window.nanoajax`.

To use this package, you can do a few things:
- Use a CommonJS-compatible module system and simply `npm install nanoajax`, and `var nanoajax = require('nanoajax')`
- Add the minified file (`nanoajax.min.js`) to your HTML as a `<script>` tag
- Concatentate the minified file (`nanoajax.min.js`) to one large JS file in your toolchain. Re-minifying later has no negative effects, so there should be no need to have an unminified file.

**Comment by yanatan16** [comment]
If this solves your problem, go ahead and close the issue.

**Comment by yanatan16** [comment]
Please reopen if you have further issues.
