### ISSUE TITLE
missing semicolons

### ISSUE THREAD

**Issue by zenmanenergy** [yanatan16/nanoajax#13]
nanoajax.min.js is missing some semicolons. I've added them and tested it, it appears to still work:

!function(e,t){function n(){if(t.XMLHttpRequest)return new t.XMLHttpRequest;try{return new t.ActiveXObject("MSXML2.XMLHTTP.3.0");}catch(e){}throw new Error("no xmlhttp request able to be created");}function r(e,t,n){e[t]=e[t]||n;}t.nanoajax=e,e.ajax=function(e,t){"string"==typeof e&&(e={url:e});var a=e.headers||{},o=e.body,u=e.method||(o?"POST":"GET"),i=e.withCredentials||!1,s=n();s.onreadystatechange=function(){4==s.readyState&&t(s.status,s.responseText,s);},o&&(r(a,"X-Requested-With","XMLHttpRequest"),r(a,"Content-Type","application/x-www-form-urlencoded")),s.open(u,e.url,!0),s.withCredentials=i;for(var c in a)s.setRequestHeader(c,a[c]);s.send(o);};}({},function(){return this;}());

**Comment by yanatan16** [comment]
Semicolons are not required for javascript to work. See the [ECMAScript Language Specification](http://www.ecma-international.org/ecma-262/5.1/#sec-7.9).
